### ISSUE TITLE
Plans for adopting Korean Letter cases?

### ISSUE THREAD

**Issue by withoutwax** [cmiscm/leonsans#11]
Hello!

Congratulations with the new project! Love your work.
Do you have plans to adopt Korean typeface system to this font?

**Comment by cmiscm** [comment]
There are so many glyph for Hangul, it's not easy to design all of them alone. But as a Korean, I would like to design it someday.

**Comment by withoutwax** [comment]
I totally agree - Hangul just have so many complexity and combination to consider but definitely would love to see it come true 😊
Thank you for sharing your work with the community! 
Excited to see how this project will evolve in the future 🙌🏼
