### ISSUE TITLE
Ligatures?

### ISSUE THREAD

**Issue by elijah-penney** [cmiscm/leonsans#13]
I'd love to use this font in VS Code and one of the great features to have for it is ligatures.

Example:
https://hilton.org.uk/blog/fira-code.svg

**Comment by bbbooo313** [comment]
示例：[dapingtai4455.com](dapingtai4455.com)

**Comment by cmiscm** [comment]
I'm working on to export the font to OTF, maybe you can use it with the actual font file.

**Comment by chrleon** [comment]
@elijah-penney why would you want to use it as a code editor font? A good editor font is mono-spaced. Leonsans is not. 

@cmiscm freaking love the project! Good work!
