### ISSUE TITLE
Polish chars

### ISSUE THREAD

**Issue by lukaszflorczak** [cmiscm/leonsans#16]
Could you also add Polish chars? 
`ą`, `ę`, `ł`, `ń`, `ś`, `ź`, `ż`,
`Ą`, `Ę`, `Ł`, `Ń`, `Ś`, `Ź`, `Ż`

Thank you in advance!

**Comment by cmiscm** [comment]
I'll update after my busy work is done :)

**Comment by Uranbold** [comment]
I really wanna see Cyrillic fonts. How can I add it?
