### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by amhunt** [cmiscm/leonsans#2]
When I add the simple example under `Usage` in the README, I see the below image (without animation): 
<img width="358" alt="Screen Shot 2019-08-31 at 4 29 58 PM" src="https://user-images.githubusercontent.com/12832034/64070038-aa478b00-cc0c-11e9-9745-9817f6debf08.png">

Any ideas what might be going wrong? I followed the usage steps exactly 😕

**Comment by cmiscm** [comment]
You may need to set the canvas size first. I've update my example for that.
