### ISSUE TITLE
How add a few different leon's element on page?

### ISSUE THREAD

**Issue by mevius6** [cmiscm/leonsans#20]
Without using additional libs or iframes?
Started trying, but… )
https://github.com/mevius6/test-leonsans

**Comment by cmiscm** [comment]
You can create several LeonSans class, like
const leon1 = new LeonSans();
const leon2 = new LeonSans();

**Comment by mevius6** [comment]
Ok, I'll try later )
Thanks for the answer and for sharing your work )
