### ISSUE TITLE
Great :)

### ISSUE THREAD

**Issue by omarali-me** [cmiscm/leonsans#4]
Hey Kim

Congratulations on Leon and this is a beautiful font and a beautiful way to celebrate the birth of your son :)

**Comment by cmiscm** [comment]
Thank you :)

**Comment by kidkkr** [comment]
I wonder what tools you used to design fonts.

**Comment by cmiscm** [comment]
adobe illustrator

**Comment by S-n-d** [comment]
Congratulations! Kudos for the nice work.

**Comment by Emelino** [comment]
Awsome job !!
