### ISSUE TITLE
TTF version?

### ISSUE THREAD

**Issue by scottybo** [cmiscm/leonsans#5]
I appreciate the whole point of this font is that it's dynamically generated, but we're curious about using it as a font for a brand. In this instance, we'd need to be able to use it in an old fashioned Adobe scenario - is there a way to output a traditional TTF / OTF etc file?

**Comment by cmiscm** [comment]
I'm actually working on with Google Font team for that. I think the best way is that export all the types to SVG and convert it to OTF. You may can get the font file on Google Font website if I can success to convert it.

**Comment by scottybo** [comment]
Thanks for the speedy response!

Do you have any tips on how we would export as SVG?

**Comment by cmiscm** [comment]
https://gliffy.github.io/canvas2svg/ it works well, I may can add this one to my examples

**Comment by scottybo** [comment]
That would be amazing!

**Comment by sammdu** [comment]
Yes I love the idea of having the option of actual font files!
@cmiscm please release TTF/OTF versions of this beautiful font.

I love Geometric Sans fonts but haven't came across many good ones. So far Publica Sans is the closest to the pure, geometric look that I'm going after. Your font is basically perfect for my aesthetic, and I would love to be able to use them in my design!

**Comment by skeeterdoodles** [comment]
Hello - I feel like this is the perfect font for me HOWEVER I would need the traditional TTF / OTF to have consistent branding. Please let us know if you ever publish the  traditional TTF / OTF. Excellent work - you are very talented!

**Comment by ynotdraw** [comment]
+1 would love to use this if served up via google fonts!

**Comment by Droyk** [comment]
Any news? @scottybo

**Comment by scottybo** [comment]
Not sure why I would have any news @Droyk !

**Comment by sammdu** [comment]
@scottybo @Droyk hey it seems like the author did create OTF versions!
https://github.com/cmiscm/leonsansfont

**Comment by Droyk** [comment]
Yup, my bad! @sammdu @scottybo
