### ISSUE TITLE
Add diacritics support

### ISSUE THREAD

**Issue by DennisGaida** [cmiscm/leonsans#7]
It would be great if you added [diacritics](https://en.wikipedia.org/wiki/Diacritic) to this font. Especially the most common (http://www.ukstudentlife.com/Life/Computer/European.htm) ones would help a lot of users and aren't too complicated to add (like é, ü, ê).

**Comment by tarikkavaz** [comment]
How about "Latin Extended"

**Comment by cmiscm** [comment]
I'll update  ĉ ĝ ĥ ĵ ŝ ŭ, what is the most used letters?

**Comment by DennisGaida** [comment]
I don’t know about most used but check out ISO 8859-1   https://en.m.wikipedia.org/wiki/ISO/IEC_8859-1  with that charset you are safe for a lot of Western European languages (e.g. Spanish, French, German etc.). If you wanna be really cool check out the extended version ISO/IEC 8859-15 which includes even better coverage of more languages.
Personally I‘d be happy with adding German support, so äöü-Umlauts and the strange ß letter.

**Comment by tarikkavaz** [comment]
> I'll update ĉ ĝ ĥ ĵ ŝ ŭ, what is the most used letters?

could you add these too? 

Ğğ İı Şş Çç

**Comment by DennisGaida** [comment]
❤ great!
